theme: jekyll-theme-slate

name: Kitsap Forest Theater
title: Kitsap Forest Theater
remote_theme: ronv/ultra

livereload: true
baseurl: /Kitsap-Forest-Theater

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: "" # an empty string means all files
    values:
      layout: "default"

  - scope:
      path: "img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - maps
  - reference
